search_type: dynamic_beam_search # 根據search_type選擇對應的搜尋方法配置

contrastive_search:
  search_kind: contrastive
  beam_width: [ 95, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500 ]
  #[ 95, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000 ]
  batch_size: 500
  prompt_template_id: 3
  vocab_limit: true
  precistion: half
  eos_threshold: 0.0001
  max_guess_number: 50
  min_len: 8
  output_path: gen
  output_file_name: contrastive_search_results.jsonl

dynamic_beam_search:
  beam_width: [ 95, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500, 500 ]
  #[ 95, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000, 1000 ]
  batch_size: 100
  prompt_template_id: 3
  vocab_limit: true
  precistion: half
  eos_threshold: 0.001
  max_guess_number: 1000
  min_len: 7
  output_path: gen
  output_file_name: dynamic_beam_search_results.jsonl

eval:
  model_path: checkpoints/Qwen3-4B/run_3/lora_final
  #checkpoints/Llama-3.2-3B-Instruct/run_4/lora_final
  # eval-only fields _contrastive.jsonl
  test_data_path: datasets/processed/semanticPCFG/000webhost/backoff/split/test_data.jsonl
  max_eval_samples: 20 # 外層迴圈：評估幾筆測試密碼（全量 53K 太慢）
  eval_output_file_name: eval_results_Qwen.jsonl
